apiVersion: v1
kind: Service 
metadata:
  name: mongo # must be mongo! since flask need this DNS name 
# connect to the db. coz of MONGO_HOST: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP