apiVersion: v1
kind: Service
metadata:
  name: todo-web-service
spec:
  selector:
    app: todo-web
  ports:
    - port: 5000
      targetPort: 5000
  type: NodePort # this is more for test only. In real 
# scenario, maybe loadBalancer is more proper