apiVersion: v1
kind: Service
metadata:
  name: todo-web-service
spec:
  selector:
    app: todo-web
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer # here we use load balancer
# instead of test-only nodeport