# web deployment 这一块！
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: todo-web
          image: jaydenx21/todo-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongo
            - name: MONGO_PORT
              value: "27017"
            - name: FLASK_ENV
              value: "production"
            - name: PORT
              value: "5000"